name: guide_my_steps
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  google_map_repository:
    path: packages/google_map_repository
  bloc:
    path: ../packages/bloc
  equatable: ^2.0.3
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc:
    path: ../packages/flutter_bloc
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^3.0.1
  meta: ^1.7.0
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.0
  get_it: ^7.2.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/img.png
    - images/guia.png
    - images/lugar.png
dependency_overrides:
  bloc:
    path: ../packages/bloc
  bloc_test:
    path: ../packages/bloc_test
  flutter_bloc:
    path: ../packages/flutter_bloc
