name: google_map_repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
    google_maps_flutter: ^2.0.3
    geolocator: ^9.0.1
    geocoding: ^2.0.0
    flutter_polyline_points: ^1.0.0
    json_serializable: ^6.1.5
    http: ^0.13.4
    dio: ^4.0.0
    get_it: ^7.2.0

dev_dependencies:
  very_good_analysis: ^3.0.1
